type = "web_pixel_extension"
name = "web-pixel"

runtime_context = "strict"

[settings]
type = "object"

[settings.fields.accountID]
name = "2547157494654494"
description = "2547157494654494"

# name = "25471574946544941"
# description = "25471574946544941"

type = "single_line_text_field"
validations = [{ name = "min", value = "1" }]
